config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'
  post 'post/create', to: 'posts#create', as: 'post_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :image, presence: true
  validates :content, presence: true

  before_save :ban_word

  def ban_word
    self.content.gsub!("spoiler", "")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def create
    @post = Post.create(
      title: params['title'],
      content: params['content'],
      image: params['image']
    )
    if @post.save
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class= "container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Blog</h1>
<h2>ingreso de un nuevo post</h2>
<br>
<div>
<%= form_with(url: post_create_path, model: @post , local: true)do |f| %>
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= f.label :titulo %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group col-md-8">
      <%= f.label :contenido %>
      <%= f.text_field :content, class: 'form-control'  %>
    </div>
  </div>
  <%= f.label :imagen %>
  <%= f.text_field :image, class: 'form-control' %>
  
  <br>
  <%= f.submit "Crear Post" ,class:'btn btn-primary'%>
  
<% end %>
</div>
<br>

<h2>Todos los Post</h2>
<% @posts.each do|post| %>
<div class="card mb-3 mx-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <%= image_tag post.image, class: "img-fluid" %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><%= post.title %></h5>
        <p class="card-text"><%= post.content %></p>
        <p class="card-text"><small class="text-muted"> <%= post.created_at %> </small></p>
      </div>
    </div>
  </div>
</div>

<% end %>